# Generated by Django 5.2.17 on 2026-09-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=160)),
                ('org', models.CharField(max_length=160)),
                ('year', models.CharField(max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('cat', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=80)),
                ('icon', models.CharField(max_length=16)),
                ('thumb', models.CharField(default='bt1', max_length=16)),
                ('featured', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=220)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=80)),
                ('date', models.CharField(max_length=40)),
                ('read', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=8)),
                ('brand', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=220)),
                ('body', models.TextField()),
                ('metrics_json', models.JSONField(default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240)),
                ('answer', models.TextField()),
                ('group', models.CharField(default='home', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('service', models.CharField(blank=True, max_length=160)),
                ('budget', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(default='contact', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('number', models.CharField(max_length=8)),
                ('icon', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('short', models.CharField(max_length=80)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('tags', models.TextField(help_text='Comma-separated tags')),
                ('result_value', models.CharField(max_length=40)),
                ('result_label', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='GrowPlus+', max_length=80)),
                ('phone', models.CharField(default='+91 – 9671718434', max_length=80)),
                ('email', models.EmailField(default='Info@growplused.com', max_length=254)),
                ('website', models.CharField(default='growplused.com', max_length=120)),
                ('location', models.CharField(default='Faridabad, Haryana, India', max_length=160)),
                ('tagline', models.TextField(default="India's most results-obsessed digital marketing agency.")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(max_length=80)),
                ('bio', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('initial', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(max_length=16)),
                ('cat', models.CharField(max_length=80)),
                ('thumb', models.CharField(default='uth1', max_length=16)),
                ('title', models.CharField(max_length=220)),
                ('excerpt', models.TextField()),
                ('date', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WhyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
