export const NAV = [
  { href: "/admin", label: "Overview" },
  { href: "/admin/site", label: "Site settings" },
  { href: "/admin/services", label: "Services" },
  { href: "/admin/blogPosts", label: "Blog" },
  { href: "/admin/updates", label: "Updates" },
  { href: "/admin/faqs", label: "FAQs" },
  { href: "/admin/contactFaqs", label: "Contact FAQs" },
  { href: "/admin/team", label: "Team" },
  { href: "/admin/cases", label: "Case studies" },
  { href: "/admin/testimonials", label: "Testimonials" },
  { href: "/admin/tools", label: "Tools" },
  { href: "/admin/partners", label: "Partners" },
  { href: "/admin/awards", label: "Awards" },
  { href: "/admin/whyPoints", label: "Why points" },
  { href: "/admin/process", label: "Process" },
  { href: "/admin/inbox", label: "Inbox" },
];

export const FIELDS = {
  services: [
    { key: "slug", label: "Slug", type: "text" },
    { key: "number", label: "Number", type: "text" },
    { key: "icon", label: "Icon", type: "text" },
    { key: "title", label: "Title", type: "text" },
    { key: "short", label: "Short label", type: "text" },
    { key: "summary", label: "Summary", type: "textarea" },
    { key: "description", label: "Description", type: "textarea" },
    { key: "tags", label: "Tags (comma separated)", type: "tags" },
    { key: "resultValue", label: "Result value", type: "text" },
    { key: "resultLabel", label: "Result label", type: "textarea" },
  ],
  faqs: [
    { key: "q", label: "Question", type: "text" },
    { key: "a", label: "Answer", type: "textarea" },
  ],
  contactFaqs: [
    { key: "q", label: "Question", type: "text" },
    { key: "a", label: "Answer", type: "textarea" },
  ],
  team: [
    { key: "initial", label: "Initial", type: "text" },
    { key: "name", label: "Name", type: "text" },
    { key: "role", label: "Role", type: "text" },
    { key: "bio", label: "Bio", type: "textarea" },
  ],
  cases: [
    { key: "emoji", label: "Emoji", type: "text" },
    { key: "brand", label: "Brand line", type: "text" },
    { key: "title", label: "Title", type: "text" },
    { key: "body", label: "Body", type: "textarea" },
    { key: "metrics", label: "Metrics JSON", type: "json" },
  ],
  testimonials: [
    { key: "quote", label: "Quote", type: "textarea" },
    { key: "initial", label: "Initial", type: "text" },
    { key: "name", label: "Name", type: "text" },
    { key: "role", label: "Role", type: "text" },
  ],
  tools: [
    { key: "icon", label: "Icon", type: "text" },
    { key: "name", label: "Name", type: "text" },
    { key: "desc", label: "Description", type: "text" },
  ],
  partners: [{ key: "name", label: "Name", type: "text" }],
  awards: [
    { key: "icon", label: "Icon", type: "text" },
    { key: "title", label: "Title", type: "text" },
    { key: "org", label: "Organization", type: "text" },
    { key: "year", label: "Year", type: "text" },
  ],
  whyPoints: [
    { key: "num", label: "Number", type: "text" },
    { key: "title", label: "Title", type: "text" },
    { key: "body", label: "Body", type: "textarea" },
  ],
  process: [
    { key: "num", label: "Number", type: "text" },
    { key: "title", label: "Title", type: "text" },
    { key: "body", label: "Body", type: "textarea" },
  ],
  blogPosts: [
    { key: "slug", label: "Slug", type: "text" },
    { key: "cat", label: "Filter category", type: "text" },
    { key: "category", label: "Display category", type: "text" },
    { key: "icon", label: "Icon", type: "text" },
    { key: "thumb", label: "Thumb class", type: "text" },
    { key: "featured", label: "Featured", type: "checkbox" },
    { key: "title", label: "Title", type: "text" },
    { key: "excerpt", label: "Excerpt", type: "textarea" },
    { key: "body", label: "Body", type: "textarea" },
    { key: "author", label: "Author", type: "text" },
    { key: "date", label: "Date", type: "text" },
    { key: "read", label: "Read time", type: "text" },
  ],
  updates: [
    { key: "slug", label: "Slug", type: "text" },
    { key: "icon", label: "Icon", type: "text" },
    { key: "cat", label: "Category", type: "text" },
    { key: "thumb", label: "Thumb class", type: "text" },
    { key: "title", label: "Title", type: "text" },
    { key: "excerpt", label: "Excerpt", type: "textarea" },
    { key: "date", label: "Date", type: "text" },
  ],
};

export const TITLES = {
  services: "Services",
  faqs: "FAQs",
  contactFaqs: "Contact FAQs",
  team: "Team",
  cases: "Case studies",
  testimonials: "Testimonials",
  tools: "Tools",
  partners: "Partners",
  awards: "Awards",
  whyPoints: "Why points",
  process: "Process",
  blogPosts: "Blog posts",
  updates: "Updates",
};
